title: gbrlcardozo
baseurl: ""
description: Hi! I'm Gabriela :)<br>I like to learn about anything. I chose technology as a way of working because every day is a new day.
sass:
  style:  compressed
  sass_dir: _sass
url: 'https://gbrlcardozo.github.io'
author:
  name               : 'Gabriela Cardozo'
  email              : gabrielacardozo09@gmail.com
  github_username    : gbrlcardozo
  instagram_username : gbrlcardozo
url: 'https://gbrlcardozo.github.io'
