title: gbrlcardozo
baseurl: ""
description: 22y and learnig every day :).
sass:
  style:  compressed
  sass_dir: _sass
url: 'https://gbrlcardozo.github.io'
author:
  name               : 'Gabriela Cardozo'
  email              : gabrielacardozo09@gmail.com
  github_username    : gbrlcardozo
  instagram_username : gbrlcardozo
url: 'https://gbrlcardozo.github.io'
